### ISSUE TITLE
Zero point data calculation error

### ISSUE THREAD

**Issue by chaporovag** [dmytropaduchak/simple-linear-interpolation#1]
When set point like {x: 0, y: 0}, request for interpolated point with {x:0} is throw exception

**Comment by chaporovag** [comment]
Can't create merge request, so the problem is that you need to check coorinate variable for undefined state because coordinate is returned false if it equals 0

**Comment by chaporovag** [comment]
Please let me know when you release it with update

**Comment by dmytropaduchak** [comment]
thx you, pls use version 1.0.6
